apiVersion: apps/v1
kind: Deployment
metadata:
    name: goserver
spec:
    replicas: 5
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: goserver
                  image: whasleycardoso/teste-app:v2
                  ports:
                    - containerPort: 3000