apiVersion: v1
kind: Service
metadata:
    name: goserver-service
spec:
    type: NodePort
    ports:
        - port: 3000
          targetport: 3000
          nodeport: 80
    selector:
        app: server