apiVersion: v1
kind: Service
metadata:
    name: goserver-service
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          name: http-svc
          port: 3000
    selector:
        app: server